In [17]:
import torch
a = torch.Tensor([[1,1,1],
                  [2,2,2],
                  [3,3,3],
                  [4,4,4],
                  [5,5,5],
                  [6,6,6]])

beam_width = 3
batch_size = 2 
# a.T.reshape(3, -1).T.reshape(-1, a.shape[0], 3).permute(0,2,1).reshape(-1, a.shape[0])

In [18]:
a.reshape(beam_width,batch_size, a.size(1)).transpose(0,1).reshape(beam_width*batch_size,a.size(1))

tensor([[1., 1., 1.],
        [3., 3., 3.],
        [5., 5., 5.],
        [2., 2., 2.],
        [4., 4., 4.],
        [6., 6., 6.]])

In [12]:
a = a.reshape(3, 2, 3)
a

tensor([[[1., 1., 1.],
         [2., 2., 2.]],

        [[3., 3., 3.],
         [4., 4., 4.]],

        [[5., 5., 5.],
         [6., 6., 6.]]])

In [13]:
a = a.transpose(0,1)
a

tensor([[[1., 1., 1.],
         [3., 3., 3.],
         [5., 5., 5.]],

        [[2., 2., 2.],
         [4., 4., 4.],
         [6., 6., 6.]]])

In [14]:
a = a.reshape(6,3)
a

tensor([[1., 1., 1.],
        [3., 3., 3.],
        [5., 5., 5.],
        [2., 2., 2.],
        [4., 4., 4.],
        [6., 6., 6.]])