In [7]:
import torch
a = torch.tensor([[615, 380, 211, 934, 407],
                [615, 934, 407, 270, 380],
                [615, 380, 934, 407, 270],
                [615, 934, 407, 270, 957],
                [615, 380, 270, 407, 777],
                [615, 784, 572, 385, 380],
                [615, 572, 385, 288, 784],
                [615, 784, 784, 385, 288],
                [615, 380, 572, 385, 784],
                [615, 784, 572, 385, 589]])

bol = torch.zeros(a.shape, dtype=torch.bool)
bol[:2, 0] = True

In [8]:
bol

tensor([[ True, False, False, False, False],
        [ True, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [9]:
a[bol].reshape(-1,2).T.unsqueeze(-1), a[2:4][:, None]

(tensor([[[615]],
 
         [[615]]]),
 tensor([[[615, 380, 934, 407, 270]],
 
         [[615, 934, 407, 270, 957]]]))

In [10]:
unique_token_idx = torch.argmin((a[bol].reshape(-1,2).T.unsqueeze(-1) == a[2:4][:, None]).any(1).long(), axis=1)
a[bol].reshape(-1,2).T.unsqueeze(-1) == a[2:4][:, None] #same as above, just w/o any().long() and argmin applied

tensor([[[ True, False, False, False, False]],

        [[ True, False, False, False, False]]])

In [11]:
bol[torch.arange(2, 4), unique_token_idx] = True
bol


tensor([[ True, False, False, False, False],
        [ True, False, False, False, False],
        [False,  True, False, False, False],
        [False,  True, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

significance of this line shown below

In [12]:
a[bol].reshape(-1,2).T.unsqueeze(-1), a[4:6][:, None]

(tensor([[[615],
          [380]],
 
         [[615],
          [934]]]),
 tensor([[[615, 380, 270, 407, 777]],
 
         [[615, 784, 572, 385, 380]]]))